### ISSUE TITLE
作业直接在git上add file提交能看到吗

### ISSUE THREAD

**Issue by xiaoxinyusss** [X-lab2017/dase-2024-autumn#17]
![Uploading 微信图片_20241008185926.png…]()

**Comment by HalloMelon** [comment]
![image](https://github.com/user-attachments/assets/e505e487-8c0c-4499-a14e-3f0f6a353501)

看不了你的图片，另外在你的仓库里我也没有看到文件。

![image](https://github.com/user-attachments/assets/1bf2096c-a196-4295-aea5-914cb755c4f1)

**Comment by Tenth-crew** [comment]
作业最后在仓库可见就可以

**Comment by xiaoxinyusss** [comment]
好的，谢谢老师!
